#!/bin/sh
 
# PROVIDE: velma_polybeta
# REQUIRE: LOGIN FILESYSTEMS
# KEYWORDS: start stop restart status poll enabled rcvar

 
. /etc/rc.subr
 
instance_name="polybeta"
name="velma_$instance_name"
rcvar=`set_rcvar`
command=daemon
pidfile="/var/run/${name}.pid"
start_cmd="$command -c -u velmad -r -P $pidfile -- /usr/local/bin/$name -flagfile /etc/velma/$instance_name.conf >/var/log/${name}.log"
#stop_cmd=":"



load_rc_config $name
run_rc_command "$1"
